def get_fqe_doc_content() -> str:
    return (
        "FQE – Faculty Quality & Experience (20 marks)\n"
        "===========================================\n\n"
        "Step 1: What is FQE?\n"
        "--------------------\n"
        "FQE is a 20-mark sub-parameter under NIRF’s Teaching, Learning & Resources (TLR). It tells us how strong the faculty body is in two ways:\n"
        "  • FQ  – how many faculty members have a PhD.\n"
        "  • FE  – how balanced the faculty is in terms of experience.\n\n"
        "A higher FQE score means:\n"
        "  • Enough PhD-qualified faculty for the student intake.\n"
        "  • A healthy mix of junior, mid-level, and senior faculty.\n\n"
        "Step 2: What inputs does this calculator use?\n"
        "-------------------------------------------\n"
        "For the latest academic year we use:\n"
        "  1. Total Faculty                → all full-time faculty members.\n"
        "  2. Faculty with PhD             → faculty who hold a PhD (or equivalent).\n"
        "  3. Total Students (UG + PG)     → used to estimate how many faculty are needed.\n"
        "  4. Faculty with exp ≤ 8 years   → junior faculty.\n"
        "  5. Faculty with exp 8–15 years  → mid-level faculty.\n"
        "  6. Faculty with exp > 15 years  → senior faculty.\n\n"
        "You just enter these counts. The assistant converts them into percentages and scores internally.\n\n"
        "Step 3: How do we read FQ (Faculty Qualification)?\n"
        "-------------------------------------------------\n"
        "FQ checks how many of the REQUIRED faculty positions are filled by PhD-qualified staff. Conceptually, we assume a 1:15 norm (1 faculty for every 15 students):\n"
        "  • Required Faculty  ≈  Total Students ÷ 15\n"
        "  • We compare PhD faculty against the higher of:\n"
        "      – Actual Faculty, and\n"
        "      – Required Faculty.\n"
        "  • This gives FRA, the percentage of PhD faculty with respect to what is expected.\n\n"
        "If FRA is close to or above 95%, FQ is close to the maximum 10 marks.\n"
        "If FRA is low, the FQ part of FQE is also low.\n\n"
        "Step 4: How do we read FE (Faculty Experience)?\n"
        "---------------------------------------------\n"
        "FE looks at the experience distribution. NIRF prefers a balanced mix of:\n"
        "  • F1: Junior  (≤ 8 years).\n"
        "  • F2: Mid     (8–15 years).\n"
        "  • F3: Senior  (> 15 years).\n\n"
        "Roughly, a 1 : 1 : 1 mix (around 33% each) is ideal. This shows:\n"
        "  • new talent is coming in,\n"
        "  • mid-career faculty are being retained,\n"
        "  • there is a stable senior core.\n\n"
        "In NIRF scoring:\n"
        "  • Juniors (F1) can contribute up to 3 marks.\n"
        "  • Mid-level (F2) can contribute up to 3 marks.\n"
        "  • Seniors (F3) can contribute up to 4 marks.\n\n"
        "Step 5: Final FQE score – how to interpret it\n"
        "--------------------------------------------\n"
        "FQE is simply:\n"
        "  • FQE = FQ + FE   (maximum 20 marks).\n\n"
        "Think of it like this:\n"
        "  • FQ  → depth of academic qualification (PhDs).\n"
        "  • FE  → stability and maturity of the faculty team.\n\n"
        "A high FQE (e.g., 17–20) usually means:\n"
        "  • Enough PhD faculty for the current student load, and\n"
        "  • A well-balanced experience mix.\n\n"
        "A low FQE suggests:\n"
        "  • Need to recruit more PhD-qualified faculty, and/or\n"
        "  • Need to correct imbalances in experience (e.g., too many juniors, too few seniors).\n\n"
        "Step 6: Do we use any machine learning here?\n"
        "-------------------------------------------\n"
        "No. FQE is based entirely on the official NIRF formula. All calculations (FQ, FE, and FQE) are done directly from our inputs.\n\n"
        "This means:\n"
        "  • No training data is required.\n"
        "  • For the same inputs, you always get the same FQE score.\n"
        "  • The calculation is fully transparent and easy to audit.\n\n"
        "Step 7: A simple numerical example\n"
        "---------------------------------\n"
        "Below is a clear, formula‑based calculation using simple inputs.\n\n"
        "Example Input (1 year):\n"
        "  • Total Students (TS)      = 2,186\n"
        "  • Total Faculty (TF)       = 240\n"
        "  • PhD Faculty (PHD)        = 106\n"
        "  • Faculty ≤ 8 yrs exp      = 143\n"
        "  • Faculty 8–15 yrs exp     = 59\n"
        "  • Faculty > 15 yrs exp     = 38\n\n"
        "---------------------------------\n"
        "A) REQUIRED FACULTY (RF)\n"
        "Formula:\n"
        "  RF = TS / 15\n\n"
        "Calculation:\n"
        "  RF = 2186 / 15 ≈ 146\n\n"
        "We now compare:\n"
        "  Max(TF, RF) = Max(240, 146) = 240\n\n"
        "This value (240) becomes the denominator when computing FQ.\n\n"
        "---------------------------------\n"
        "B) FQ — FACULTY QUALIFICATION SCORE\n"
        "Formula for FRA:\n"
        "  FRA = (PHD / Max(TF, RF)) × 100\n\n"
        "Calculation:\n"
        "  FRA = (106 / 240) × 100 ≈ 44.17%\n\n"
        "Now apply FQ formula:\n"
        "  If FRA < 95:\n"
        "      FQ = 10 × (FRA / 95)\n\n"
        "Thus:\n"
        "  FQ = 10 × (44.17 / 95) ≈ 4.65\n\n"
        "---------------------------------\n"
        "C) FE — FACULTY EXPERIENCE SCORE\n"
        "Step 1 → Compute fractions:\n"
        "  F1 = 143 / 240 ≈ 0.596   (≤ 8 yrs)\n"
        "  F2 =  59 / 240 ≈ 0.246   (8–15 yrs)\n"
        "  F3 =  38 / 240 ≈ 0.158   (> 15 yrs)\n\n"
        "Step 2 → Apply NIRF formula:\n"
        "  FE = 3 × min(3F1, 1) + 3 × min(3F2, 1) + 4 × min(3F3, 1)\n\n"
        "Compute each component:\n"
        "  3F1 = 3 × 0.596 = 1.788 → min = 1\n"
        "  Component1 = 3 × 1 = 3\n\n"
        "  3F2 = 3 × 0.246 = 0.738 → min = 0.738\n"
        "  Component2 = 3 × 0.738 = 2.214\n\n"
        "  3F3 = 3 × 0.158 = 0.474 → min = 0.474\n"
        "  Component3 = 4 × 0.474 = 1.896\n\n"
        "Thus:\n"
        "  FE = 3 + 2.214 + 1.896 = 7.11\n\n"
        "---------------------------------\n"
        "D) FINAL FQE SCORE\n"
        "Formula:\n"
        "  FQE = FQ + FE\n\n"
        "Calculation:\n"
        "  FQE = 4.65 + 7.11 = 11.76 (out of 20)\n\n"
        "---------------------------------\n"
    )