def get_ss_doc_content() -> str:
    return (
        "SS – Student Strength (20 marks)\n"
        "===========================================\n\n"
        "Step 1: What is Student Strength (SS)?\n"
        "-------------------------------------\n"
        "Student Strength (SS) is a 20-mark sub-parameter under the Teaching, Learning & Resources (TLR) category in the NIRF ranking framework.\n"
        "It evaluates the size and engagement of the student body in an institution, reflecting both capacity and actual enrollment.\n\n"
        "Step 2: Key Definitions\n"
        "------------------------\n"
        "  • NT: Total number of sanctioned seats across all programs.\n"
        "  • NE: Number of students actually enrolled in these programs.\n"
        "  • NP: Number of research scholars (PhD and equivalent) enrolled.\n\n"
        "Step 3: Understanding the SS Formula\n"
        "------------------------------------\n"
        "The SS score is calculated using the formula:\n"
        "\n"
        "    SS = f(NT, NE) × 15 + f(NP) × 5\n"
        "\n"
        "Here, f(NT, NE) and f(NP) are functions that transform the raw counts into normalized scores.\n"
        "These functions adjust for variations in institution size and ensure fair comparison.\n\n"
        "Step 4: Why Use f-Functions and an ML Model?\n"
        "--------------------------------------------\n"
        "The transformation functions f(NT, NE) and f(NP) are derived using a machine learning model.\n"
        "This model captures complex relationships between student numbers and quality indicators, providing a more accurate and equitable scoring.\n\n"
        "Step 5: Example Calculation\n"
        "---------------------------\n"
        "Suppose an institution has:\n"
        "  - NT (sanctioned seats): 2186\n"
        "  - NE (enrolled students): 2160\n"
        "  - NP (research scholars): 1\n"
        "\n"
        "The ML model computes:\n"
        "  - f(NT, NE) = 0.85\n"
        "  - f(NP) = 0.75\n"
        "\n"
        "Then,\n"
        "  SS = 0.85 × 15 + 0.75 × 5 = 12.75 + 3.75 = 10.17 (out of 20)\n\n"
        "Step 6: Summary\n"
        "---------------\n"
        "Student Strength (SS) quantifies both the capacity and actual student engagement of an institution.\n"
        "By applying ML-derived transformation functions, SS ensures a balanced evaluation that reflects institutional scale and research activity.\n"
        "This metric plays a significant role in the overall NIRF ranking."
    )