def get_fsr_doc_content():
    return (
        "=============================\n"
        "   FSR Documentation (NIRF)\n"
        "=============================\n\n"

        "Step 1: What is FSR?\n"
        "--------------------\n"
        "FSR (Faculty–Student Ratio) is a 30-mark sub-parameter under the Teaching, Learning\n"
        "and Resources (TLR) category in NIRF. It checks whether the institution has enough\n"
        "full-time qualified faculty compared to the number of students. A better ratio means\n"
        "better academic support and teaching quality.\n\n"

        "Step 2: Official Formula\n"
        "------------------------\n"
        "NIRF calculates FSR using the formula:\n\n"
        "    FSR = 30 × [15 × (F / N)]\n\n"
        "Where:\n"
        "  • F = Total full-time regular faculty in the institution.\n"
        "  • N = Total number of students = NT + NP\n"
        "       - NT = Total sanctioned approved intake (UG + PG)\n"
        "       - NP = Total number of PhD students enrolled\n\n"

        "Step 3: Important Notes from NIRF\n"
        "---------------------------------\n"
        "• Only full-time faculty who taught in both semesters are counted.\n"
        "• Faculty must have at least M.Tech/M.E./PhD. Bachelor's degree holders are excluded.\n"
        "• Expected best ratio: 1 Faculty per 15 Students.\n"
        "• If the ratio becomes F/N < 1/50, NIRF sets FSR = 0.\n\n"

        "Step 4: Inputs Required in Our Calculator\n"
        "-----------------------------------------\n"
        "To compute FSR, we require three simple values:\n"
        "  1. Total Sanctioned Seats (NT)\n"
        "  2. Total Enrolled Seats (NE) – for reference only\n"
        "  3. Total Full-Time Faculty (F)\n"
        "  4. Total PhD Students (NP)\n\n"
        "Our calculator uses NT, NP, and F directly in the formula.\n\n"

        "Step 5: Step-by-Step Example Calculation\n"
        "----------------------------------------\n"
        "Suppose an institution has:\n"
        "  - NT = 2186  (Sanctioned seats)\n"
        "  - NE = 2160  (Enrolled students – not used directly in formula)\n"
        "  - NP = 1     (PhD students)\n"
        "  - F  = 240   (Full-time regular faculty)\n\n"

        "Step 5.1 — Compute Total Students (N):\n"
        "    N = NT + NP\n"
        "    N = 2186 + 1 = 2187\n\n"

        "Step 5.2 — Compute Faculty–Student Ratio:\n"
        "    F / N = 240 / 2187 ≈ 0.1097\n\n"

        "Step 5.3 — Apply the NIRF Formula:\n"
        "    FSR = 30 × [15 × (F/N)]\n"
        "    FSR = 30 × [15 × 0.1097]\n"
        "    FSR = 30 × 1.6455\n"
        "    FSR ≈ 49.36\n\n"

        "Step 5.4 — Apply Lower Bound Rule:\n"
        "If F/N < 1/50 (0.02), then FSR = 0.\n"
        "Here, F/N = 0.1097 > 0.02, so the score is valid.\n\n"

        "Final FSR Score ≈ 49.36 (before NIRF normalization)\n\n"

        "Step 6: Understanding the Score\n"
        "-------------------------------\n"
        "• A high FSR score means the institution has ample full-time faculty.\n"
        "• A low FSR score means either:\n"
        "     1. Too many students, or\n"
        "     2. Too few qualified full-time faculty.\n\n"

        "Step 7: Quick Improvement Summary\n"
        "---------------------------------\n"
        "• Hiring more full-time qualified faculty increases FSR.\n"
        "• Reducing sanctioned intake (NT) increases faculty–student ratio, but is rarely used.\n"
        "• Increasing PhD enrolment increases NP, slightly reducing FSR, but strengthens the\n"
        "  research environment.\n"
        "• Ensure accurate reporting: faculty must have taught both semesters.\n\n"

        "Step 8: Example Summary Table\n"
        "------------------------------\n"
        "  +----------------------+--------+--------------------------------------+\n"
        "  | Component            | Value  | Explanation                          |\n"
        "  +----------------------+--------+--------------------------------------+\n"
        "  | NT                   | 2186   | Sanctioned Intake                    |\n"
        "  | NP                   | 1      | PhD Students                         |\n"
        "  | F (Faculty)          | 240    | Full-Time Regular Faculty            |\n"
        "  | N = NT + NP          | 2187   | Total Students                       |\n"
        "  | F/N                  | 0.1097 | Faculty Density                      |\n"
        "  | FSR Score            | 49.36  | NIRF Weighted Score                  |\n"
        "  +----------------------+--------+--------------------------------------+\n"
    )